# Generated by Django 3.1.7 on 2021-04-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPers',
        ),
    ]
